[project]
name = "superbank-mcp"
version = "0.1.0"
description = "Superbank MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.25.0",
]
